development:
  adapter: postgresql
  encoding: unicode
  database: HerokuPractice
  pool: 5
  port: 5432
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: HerokuPractice
  pool: 5
  port: 5432
  host: localhost